### PR TITLE
Improve makefile

### LINKED ISSUE #21: Fix running benchmark
I find that on Windows (at least), if you try to do
$ make benchmark
it crashes out with this:

$ bundle exec ruby -I lib:ext -r fast_polylines ./perf/benchmark.rb
Traceback (most recent call last):
        3: from ./perf/benchmark.rb:3:in `<main>'
        2: from ./perf/benchmark.rb:3:in `require'
        1: from D:/qxp/bbt_proj/fast-polylines/lib/fast_polylines.rb:3:in `<top (required)>'
D:/proj/fast-polylines/lib/fast_polylines.rb:3:in `require': cannot load such file -- fast_polylines/fast_polylines (LoadError)

From what I see, the Makefile has:
In the Makefile, I see this:
> RUBY_FLAG = -I lib:ext -r $(EXT_NAME)
> benchmark: ext
>	bundle exec ruby $(RUBY_FLAG) ./perf/benchmark.rb

This does not have the lib directory on it and so (it appears that) it fails with the above error.

The fix is simple:
> RUBY_FLAG = -I lib:ext -I lib -r $(EXT_NAME)

I'm keen to know if this is a problem that you also see or is it just me?

Thanks!

### PR DESCRIPTION
**Pull request by BuonOmo**
Greatly improved by [timberio/vector]'s makefile.

- Add Windows detection.
- Fix ruby loadpath option.
- Add a `make help` utility.

Fixes #21

[timberio/vector]: https://github.com/timberio/vector

### CODE REVIEW

**Review by goodtouch — APPROVED** [review]
LGTM!

**Comment by BuonOmo** [comment]
@mohits, could you take a look at that one ?

**Comment by mohits** [comment]
Hi @BuonOmo  - sorry, I was on leave for a couple of days and busy because of that!

Ok! I tried the branch and it works fine on Windows / Ruby 2.6.
Of course, I needed to add the fix from #20 into the C file to get it to build. Once I did that, I was able to get it to build and install, and was also able to do `make benchmark` that run successfully this time!

However, one minor note. I saw this on the command line:
`bundle exec ruby -I lib";"ext -r fast_polylines ./perf/benchmark.rb`
It shows the ';' in double quotes. It obviously works with that but just looks strange.

Thanks for waiting. Happy to see Windows properly supported (other than #20)

**Comment by BuonOmo** [comment]
Thank you both ! @mohits I've removed the quotes

**Pull request merged**
