### PR TITLE
Fix broken link to upgrade section on README

### PR DESCRIPTION
**Pull request by jsantos**
Bumped into this while trying to get into the upgrade instructions

### CODE REVIEW

**Comment by jsantos** [comment]
Btw, after upgrading the gem on a Rails project I was only able to properly use 2.0.0 by specifying on the Gemfile:

`gem 'fast-polylines', require: "fast_polylines/fast_polylines"`

Should I update this on the README too?

**Comment by JamesChevalier** [comment]
I was able to get by with `gem "fast-polylines", require: "fast_polylines"`.

I'm not very well versed in how Rails `require` works, but after reading [How Does Rails Handle Gems?](https://www.justinweiss.com/articles/how-does-rails-handle-gems/) I'm thinking that this has something to do with the internal change from `fast-polylines` to `fast_polylines` and how that differs from the gem's name.

**Comment by jsantos** [comment]
@JamesChevalier Yes, that works too! I noticed pull request #14 is addressing the hyphen to underscore correction on the README.

**Review by BuonOmo — APPROVED** [review]
Thanks for the quick fix! We'll be addressing all other (some related) issues soon :)

**Pull request merged**
